import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/shared/components/common/theme-provider";
import { rocGrotesk, rocGroteskCond, rocGroteskWide } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${rocGrotesk.variable} ${rocGroteskCond.variable} ${rocGroteskWide.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}